export enum TypeActeur {
  STRUCTURE_SANTE = 'STRUCTURE_SANTE',
  ONG = 'ONG',
  POPULATION_RURALE = 'POPULATION_RURALE'
}

export enum TypeStructure {
  HOPITAL = 'HOPITAL',
  CENTRE_SANTE = 'CENTRE_SANTE',
  DISPENSAIRE = 'DISPENSAIRE',
  CLINIQUE = 'CLINIQUE',
  MATERNITE = 'MATERNITE',
  LABORATOIRE = 'LABORATOIRE'
}

export enum DomaineIntervention {
  SANTE_PUBLIQUE = 'SANTE_PUBLIQUE',
  PREVENTION_MALADIES = 'PREVENTION_MALADIES',
  NUTRITION = 'NUTRITION',
  HYGIENE_ASSAINISSEMENT = 'HYGIENE_ASSAINISSEMENT',
  SANTE_MATERNELLE = 'SANTE_MATERNELLE',
  VACCINATION = 'VACCINATION',
  LUTTE_PALUDISME = 'LUTTE_PALUDISME',
  EDUCATION_SANITAIRE = 'EDUCATION_SANITAIRE'
}

export enum Sexe {
  MASCULIN = 'MASCULIN',
  FEMININ = 'FEMININ'
}

export enum TypeCampagne {
  PREVENTION_PALUDISME = 'PREVENTION_PALUDISME',
  HYGIENE_EAU = 'HYGIENE_EAU',
  VACCINATION = 'VACCINATION',
  NUTRITION = 'NUTRITION',
  SANTE_MATERNELLE = 'SANTE_MATERNELLE',
  EDUCATION_SANITAIRE = 'EDUCATION_SANITAIRE',
  LUTTE_EPIDEMIE = 'LUTTE_EPIDEMIE',
  SENSIBILISATION_GENERALE = 'SENSIBILISATION_GENERALE'
}

export enum StatusCampagne {
  BROUILLON = 'BROUILLON',
  ACTIVE = 'ACTIVE',
  TERMINEE = 'TERMINEE',
  SUSPENDUE = 'SUSPENDUE',
  ANNULEE = 'ANNULEE'
}

export enum TypeMessage {

  INFORMATION = 'INFORMATION',
  SENSIBILISATION = 'SENSIBILISATION',
  PREVENTION = 'PREVENTION',
  CONSEIL = 'CONSEIL',
  RAPPEL = 'RAPPEL',
  FORMATION = 'FORMATION'
}

export enum PrioriteMessage {
  BASSE = 'BASSE',
  NORMALE = 'NORMALE',
  HAUTE = 'HAUTE',
  URGENTE = 'URGENTE'
}

export enum TypeAlerte {
  EPIDEMIE = 'EPIDEMIE',
  CONTAMINATION_EAU = 'CONTAMINATION_EAU',
  ALERTE_SANITAIRE = 'ALERTE_SANITAIRE',
  VACCINATION_URGENTE = 'VACCINATION_URGENTE',
  RUPTURE_MEDICAMENT = 'RUPTURE_MEDICAMENT',
  CATASTROPHE_NATURELLE = 'CATASTROPHE_NATURELLE',
  ALERTE_METEOROLOGIQUE = 'ALERTE_METEOROLOGIQUE'
}

export enum NiveauUrgence {
  INFO = 'INFO',
  ATTENTION = 'ATTENTION',
  ALERTE = 'ALERTE',
  URGENCE = 'URGENCE',
  CRITIQUE = 'CRITIQUE'
}

export enum TypeNotification {
  NOUVEAU_MESSAGE = 'NOUVEAU_MESSAGE',
  NOUVELLE_ALERTE = 'NOUVELLE_ALERTE',
  CAMPAGNE_DEMARREE = 'CAMPAGNE_DEMARREE',
  CAMPAGNE_TERMINEE = 'CAMPAGNE_TERMINEE',
  RAPPEL = 'RAPPEL',
  SYSTEME = 'SYSTEME'
}
